apiVersion: v1
kind: Service
metadata:
  labels:
    app: javademo-service
  name: javademo-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: javademo-service
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: javademo
  name: javademo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javademo
  template:
    metadata:
      labels:
        app: javademo
    spec:
      containers:
      - image: 192.168.100.203/test/javademo:v1
        name: javademo
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: harborsecret