apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: javademo
  name: javademo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javademo
  template:
    metadata:
      labels:
        app: javademo
    spec:
      containers:
      - image: 192.168.100.203/test/javademo:v1
        name: javademo
        ports:
        - containerPort: 8080